# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghlabels < Formula
  desc "Simple CLI tool to help manage labels across repos"
  homepage "https://clokwork.net/ghlabels/"
  version "0.1.3"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/clok/ghlabels/releases/download/v0.1.3/ghlabels_0.1.3_darwin_amd64.tar.gz"
    sha256 "a6a4ce44b0c0fd7c740ceda629d2b067bb7ad30e42fa9bf8df71de9762388ae8"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/clok/ghlabels/releases/download/v0.1.3/ghlabels_0.1.3_darwin_arm64.tar.gz"
    sha256 "13d828a445a549611d9b870400536d9fd88a05ef1b31a99f45dacfc56e0f3660"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/clok/ghlabels/releases/download/v0.1.3/ghlabels_0.1.3_linux_amd64.tar.gz"
    sha256 "7133c3700a3b2f519b0a4101f232d0c31a0f37fa2d462debbe03b9b0a81ba7ac"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/clok/ghlabels/releases/download/v0.1.3/ghlabels_0.1.3_linux_armv6.tar.gz"
    sha256 "60e3fd6973907ebd7795654dc6790d76c48766059f01b760c0339ebc27aad972"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/clok/ghlabels/releases/download/v0.1.3/ghlabels_0.1.3_linux_arm64.tar.gz"
    sha256 "c9538d84a8433ccb58a25c60f8ff1a796236430f85f41ebc93f3ce567e8bd19b"
  end

  def install
    bin.install "ghlabels"
  end

  test do
    system "#{bin}/ghlabels --help"
  end
end
